---
title: phiailab
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'phiailab

'
baseurl: 
url: https://www.example.com
paginate: 20
paginate_path: "/page/:num/"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
